# Generated by Django 4.0.2 on 2022-02-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('movie_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'movie_list',
            },
        ),
        migrations.CreateModel(
            name='MovieCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.movie', to_field='movie_id')),
            ],
            options={
                'db_table': 'movie_category_mapping',
                'unique_together': {('category_id', 'movie_id')},
            },
        ),
        migrations.CreateModel(
            name='ListMovieMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.movielist')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.movie', to_field='movie_id')),
            ],
            options={
                'db_table': 'list_movie_mapping',
                'unique_together': {('list_id', 'movie_id')},
            },
        ),
    ]
