# Generated by Django 4.0.2 on 2022-02-11 11:49
import os
import pandas as pd
from django.db import migrations


MOVIES_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
    "dataset/movies.dat"
)


def read_movies(file_path):
    return (
        pd.read_csv(file_path, sep="::", names=[
                    "movie_id", "movie_name", "category_name"], encoding='latin-1')
        .set_index(['movie_id', 'movie_name'])
        .apply(lambda x: x.str.split('|').explode()).reset_index()
    )


def get_movie_dataframe(movies_df):
    return movies_df[["movie_id", "movie_name"]].drop_duplicates().reset_index(drop=True)


def get_category_dataframe(movies_df):
    category_df = pd.DataFrame(
        movies_df["category_name"].drop_duplicates().reset_index(drop=True))
    category_df['id'] = category_df.index + 1
    return category_df


def get_movie_category_mapping_dataframe(movies_df, category_df):
    movie_category_mapping_df = movies_df.merge(
        category_df, on='category_name', how='outer')
    return movie_category_mapping_df[["movie_id", "id"]].rename(columns={'id': 'category_id'})


def append_movie_table(apps, movie_df):
    for _, row in movie_df.iterrows():
        apps.get_model('base.Movie').objects.create(
            movie_id=row['movie_id'], movie_name=row['movie_name'])


def append_category_table(apps, category_df):
    for _, row in category_df.iterrows():
        apps.get_model('base.Category').objects.create(
            category_name=row['category_name'])


def append_movie_category_mapping_table(apps, movie_category_mapping_df):
    for _, row in movie_category_mapping_df.iterrows():
        movie = apps.get_model('base.Movie').objects.get(
            movie_id=row['movie_id'])
        category = apps.get_model(
            'base.Category').objects.get(id=row['category_id'])
        apps.get_model('base.MovieCategoryMapping').objects.create(
            movie=movie, category=category)


def load_data(apps, schema_editor):
    movies_df = read_movies(MOVIES_PATH)
    movie_df = get_movie_dataframe(movies_df)
    category_df = get_category_dataframe(movies_df)
    movie_category_mapping_df = get_movie_category_mapping_dataframe(
        movies_df, category_df)

    append_movie_table(apps, movie_df)
    append_category_table(apps, category_df)
    append_movie_category_mapping_table(apps, movie_category_mapping_df)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
